import type { InsuranceFormConfig } from "@/components/InsuranceQuoteForm";

export const formConfigs: Record<string, InsuranceFormConfig> = {
  auto: {
    type: "Seguro Auto",
    emoji: "🚗",
    title: "Cotação de Seguro Auto Grátis",
    subtitle: "Encontre o melhor preço para seu veículo em minutos",
    metaTitle: "Cotação de Seguro Auto Grátis em Guarulhos | Patro Seguros",
    metaDescription: "Solicite sua cotação gratuita de Seguro Auto. Comparamos Porto, Tokio Marine, Allianz, HDI e mais 16 seguradoras. Resposta em 2 horas.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "marca", label: "Marca do Veículo", required: true, type: "select", options: ["Fiat", "Volkswagen", "Chevrolet", "Ford", "Hyundai", "Toyota", "Honda", "Renault", "Jeep", "Nissan", "Peugeot", "Citroën", "BMW", "Mercedes-Benz", "Audi", "Outra"] },
      { id: "modelo", label: "Modelo", placeholder: "Ex: Civic, Onix, HB20...", required: true, type: "text" },
      { id: "ano", label: "Ano do Veículo", required: true, type: "select", options: Array.from({ length: 17 }, (_, i) => String(2026 - i)) },
      { id: "cobertura", label: "Tipo de Cobertura", required: true, type: "radio", options: ["Compreensiva (Roubo + Colisão + Incêndio)", "Parcial (Colisão + Incêndio)", "Terceiros (Responsabilidade Civil)"] },
    ],
    benefits: [
      { icon: "⚡", title: "Resposta em 2 horas", desc: "Cotações comparativas de várias seguradoras" },
      { icon: "💰", title: "Melhores preços", desc: "Comparamos 16+ seguradoras para você" },
      { icon: "🛡️", title: "Suporte completo", desc: "Acompanhamento em sinistros do início ao fim" },
    ],
    faqs: [
      { question: "Qual o seguro auto mais barato?", answer: "O preço varia conforme perfil, veículo e região. Comparamos todas as seguradoras para encontrar o menor valor com a melhor cobertura." },
      { question: "Como reduzir o valor do seguro auto?", answer: "Instalar rastreador, ter garagem, manter bônus e escolher franquia maior são formas eficazes de reduzir o prêmio." },
      { question: "Seguro auto fica mais caro para carros financiados?", answer: "Não necessariamente. Carros financiados precisam de cobertura compreensiva, mas comparando seguradoras é possível encontrar bons preços." },
      { question: "Preciso de cobertura compreensiva?", answer: "Recomendamos compreensiva para veículos de maior valor. Para carros mais antigos, a cobertura de terceiros pode ser suficiente." },
    ],
  },
  vida: {
    type: "Seguro de Vida",
    emoji: "❤️",
    title: "Cotação de Seguro de Vida Grátis",
    subtitle: "Proteja quem você ama com a melhor cobertura",
    metaTitle: "Cotação de Seguro de Vida Grátis | Patro Seguros Guarulhos",
    metaDescription: "Solicite cotação gratuita de Seguro de Vida. Coberturas a partir de R$ 100 mil. Aprovação rápida e sem burocracia. Patro Seguros.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "nascimento", label: "Data de Nascimento", required: true, type: "date" },
      { id: "profissao", label: "Profissão", placeholder: "Sua profissão", required: true, type: "text" },
      { id: "cobertura", label: "Cobertura Desejada", required: true, type: "radio", options: ["R$ 100 mil", "R$ 250 mil", "R$ 500 mil", "R$ 1 milhão", "Outro valor"] },
      { id: "tipo", label: "Tipo de Seguro", required: true, type: "radio", options: ["Seguro de Vida Individual", "Seguro de Vida em Grupo (empresa)"] },
    ],
    benefits: [
      { icon: "🔒", title: "Proteção garantida", desc: "Cobertura desde R$ 100 mil até R$ 2 milhões" },
      { icon: "💳", title: "Prêmios acessíveis", desc: "A partir de R$ 50/mês" },
      { icon: "⚡", title: "Aprovação rápida", desc: "Sem burocracia, análise em 24h" },
    ],
    faqs: [
      { question: "Quanto custa um seguro de vida?", answer: "A partir de R$ 50/mês, dependendo da idade, profissão e valor da cobertura escolhida." },
      { question: "Seguro de vida tem carência?", answer: "Para morte natural, algumas seguradoras aplicam carência de 24 meses. Para morte acidental, a cobertura é imediata." },
      { question: "Posso ter mais de um seguro de vida?", answer: "Sim! Você pode ter múltiplos seguros de vida de seguradoras diferentes." },
    ],
  },
  residencial: {
    type: "Seguro Residencial",
    emoji: "🏠",
    title: "Cotação de Seguro Residencial Grátis",
    subtitle: "Proteja seu lar com a melhor cobertura",
    metaTitle: "Cotação de Seguro Residencial Grátis | Patro Seguros Guarulhos",
    metaDescription: "Cotação gratuita de Seguro Residencial. Proteção contra incêndio, roubo, RC e mais. Compare seguradoras. Patro Seguros.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "tipoImovel", label: "Tipo de Imóvel", required: true, type: "radio", options: ["Apartamento", "Casa", "Condomínio"] },
      { id: "valorImovel", label: "Valor Estimado do Imóvel", placeholder: "R$ 300.000", required: true, type: "currency" },
      { id: "cep", label: "CEP", placeholder: "00000-000", required: true, type: "text" },
      { id: "coberturas", label: "Coberturas Desejadas", required: true, type: "checkbox-group", options: ["Incêndio", "Roubo", "Responsabilidade Civil", "Vidros", "Todos"] },
    ],
    benefits: [
      { icon: "🔐", title: "Proteção completa", desc: "Incêndio, roubo, responsabilidade civil e vidros" },
      { icon: "📍", title: "Análise por CEP", desc: "Preço justo de acordo com sua região" },
      { icon: "🚨", title: "Sinistro 24h", desc: "Atendimento emergencial a qualquer hora" },
    ],
    faqs: [
      { question: "Seguro residencial cobre roubo?", answer: "Sim, a cobertura de roubo e furto qualificado pode ser incluída no seguro residencial." },
      { question: "Quanto custa um seguro residencial?", answer: "A partir de R$ 15/mês para apartamentos. O valor varia conforme tipo de imóvel, localização e coberturas." },
      { question: "Inquilino pode contratar seguro residencial?", answer: "Sim! Inquilinos podem contratar seguro para proteger seus bens e o conteúdo do imóvel." },
    ],
  },
  saude: {
    type: "Plano de Saúde",
    emoji: "🏥",
    title: "Cotação de Plano de Saúde Grátis",
    subtitle: "Saúde em dia, proteção garantida",
    metaTitle: "Cotação de Plano de Saúde Grátis em Guarulhos | Patro Seguros",
    metaDescription: "Compare planos de saúde das melhores operadoras. Cotação gratuita para pessoa física e empresas. Resposta em 2h. Patro Seguros.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "vidas", label: "Número de Vidas", required: true, type: "radio", options: ["1 pessoa", "2-3 pessoas", "4-5 pessoas", "6+ pessoas"] },
      { id: "faixaEtaria", label: "Faixa Etária Principal", required: true, type: "radio", options: ["Até 30 anos", "31-45 anos", "46-60 anos", "60+ anos"] },
      { id: "tipoCobertura", label: "Tipo de Cobertura", required: true, type: "radio", options: ["Básico (Ambulatorial + Hospitalar)", "Intermediário (+ Odonto)", "Premium (Tudo + Fisio + Psicologia)"] },
      { id: "temEmpresa", label: "Tem Empresa?", required: true, type: "radio", options: ["Pessoa Física", "Empresa (PME)"] },
    ],
    benefits: [
      { icon: "🏥", title: "Rede ampla", desc: "Mais de 20 operadoras e milhares de prestadores" },
      { icon: "💰", title: "Preços competitivos", desc: "Comparamos as melhores operadoras do mercado" },
      { icon: "📋", title: "Sem burocracia", desc: "Análise rápida e aprovação em 24h" },
    ],
    faqs: [
      { question: "Qual o plano de saúde mais barato?", answer: "Planos com coparticipação e rede regional costumam ter os menores valores. Comparamos todas as opções para seu perfil." },
      { question: "Empresa com 2 funcionários pode ter plano empresarial?", answer: "Sim! A maioria das operadoras aceita a partir de 2 vidas para planos PME, com preços até 40% menores." },
      { question: "Plano de saúde tem carência?", answer: "Sim, carências variam de 24h a 300 dias conforme o procedimento. Para portabilidade, as carências podem ser eliminadas." },
    ],
  },
  empresarial: {
    type: "Seguro Empresarial",
    emoji: "🏢",
    title: "Cotação de Seguro Empresarial Grátis",
    subtitle: "Proteja seu negócio com segurança total",
    metaTitle: "Cotação de Seguro Empresarial Grátis | Patro Seguros Guarulhos",
    metaDescription: "Cotação gratuita de Seguro Empresarial. Proteção para comércio, indústria e serviços. Compare seguradoras. Patro Seguros.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "razaoSocial", label: "Razão Social", placeholder: "Nome da empresa", required: true, type: "text" },
      { id: "ramo", label: "Ramo de Atividade", required: true, type: "select", options: ["Comércio", "Serviços", "Indústria", "Saúde", "Tecnologia", "Agronegócio", "Outro"] },
      { id: "faturamento", label: "Faturamento Anual Estimado", placeholder: "R$ 500.000", required: true, type: "currency" },
      { id: "coberturas", label: "Coberturas Desejadas", required: true, type: "checkbox-group", options: ["Incêndio", "Roubo", "Responsabilidade Civil", "Vidros", "Equipamentos", "Todos"] },
    ],
    benefits: [
      { icon: "🛡️", title: "Proteção total", desc: "Incêndio, roubo, RC, equipamentos e vidros" },
      { icon: "📊", title: "Análise personalizada", desc: "Cobertura de acordo com seu ramo e faturamento" },
      { icon: "⚡", title: "Resposta rápida", desc: "Cotação em até 2 horas com comparativo" },
    ],
    faqs: [
      { question: "Seguro empresarial é obrigatório?", answer: "Não é obrigatório por lei na maioria dos casos, mas é essencial para proteger o patrimônio da empresa contra imprevistos." },
      { question: "O que o seguro empresarial cobre?", answer: "Incêndio, roubo, responsabilidade civil, danos elétricos, vendaval, equipamentos e muito mais, conforme o plano escolhido." },
      { question: "Quanto custa seguro empresarial?", answer: "Depende do ramo, localização e valor segurado. Pode começar em R$ 80/mês para comércios pequenos." },
    ],
  },
  "consorcio-imoveis": {
    type: "Consórcio de Imóveis",
    emoji: "🏠",
    title: "Simulação de Consórcio de Imóveis",
    subtitle: "Realize o sonho da casa própria sem juros",
    metaTitle: "Consórcio de Imóveis em Guarulhos | Patro Seguros",
    metaDescription: "Simule seu consórcio de imóveis. Sem juros, sem entrada. Parcelas que cabem no bolso. Patro Seguros Guarulhos.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "valorCredito", label: "Valor do Crédito Desejado", required: true, type: "select", options: ["Até R$ 200 mil", "R$ 200 mil - R$ 400 mil", "R$ 400 mil - R$ 600 mil", "R$ 600 mil - R$ 1 milhão", "Acima de R$ 1 milhão"] },
      { id: "prazo", label: "Prazo Desejado", required: true, type: "radio", options: ["120 meses", "150 meses", "180 meses", "200 meses"] },
      { id: "finalidade", label: "Finalidade", required: true, type: "radio", options: ["Compra de imóvel novo", "Compra de imóvel usado", "Construção", "Reforma"] },
    ],
    benefits: [
      { icon: "🏠", title: "Sem juros", desc: "Apenas taxa de administração, muito mais barato que financiamento" },
      { icon: "💰", title: "Sem entrada", desc: "Comece a pagar sem precisar de valor de entrada" },
      { icon: "📈", title: "Poder de compra", desc: "Crédito atualizado até a contemplação" },
    ],
    faqs: [
      { question: "Consórcio de imóvel tem juros?", answer: "Não! O consórcio não cobra juros, apenas uma taxa de administração diluída nas parcelas, tornando-o mais econômico que o financiamento." },
      { question: "Como funciona a contemplação?", answer: "Você pode ser contemplado por sorteio mensal ou por lance (oferta de antecipação de parcelas)." },
      { question: "Posso usar FGTS no consórcio?", answer: "Sim! O FGTS pode ser utilizado para dar lance ou complementar o crédito na compra do imóvel." },
    ],
  },
  "consorcio-carro": {
    type: "Consórcio de Carro",
    emoji: "🚗",
    title: "Simulação de Consórcio de Carro",
    subtitle: "Seu carro novo sem juros e sem entrada",
    metaTitle: "Consórcio de Carro em Guarulhos | Patro Seguros",
    metaDescription: "Simule seu consórcio de carro. Sem juros, parcelas acessíveis. Compare administradoras. Patro Seguros Guarulhos.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "valorCredito", label: "Valor do Crédito Desejado", required: true, type: "select", options: ["Até R$ 50 mil", "R$ 50 mil - R$ 100 mil", "R$ 100 mil - R$ 150 mil", "R$ 150 mil - R$ 200 mil", "Acima de R$ 200 mil"] },
      { id: "prazo", label: "Prazo Desejado", required: true, type: "radio", options: ["60 meses", "72 meses", "84 meses", "100 meses"] },
      { id: "tipoVeiculo", label: "Tipo de Veículo", required: true, type: "radio", options: ["Carro novo (0km)", "Carro seminovo", "Ainda não decidi"] },
    ],
    benefits: [
      { icon: "🚗", title: "Sem juros", desc: "Economize até 40% comparado ao financiamento" },
      { icon: "💳", title: "Parcelas acessíveis", desc: "Planos que cabem no seu bolso" },
      { icon: "⚡", title: "Contemplação rápida", desc: "Possibilidade de lance para antecipar" },
    ],
    faqs: [
      { question: "Consórcio de carro vale a pena?", answer: "Sim! Sem juros, o consórcio pode ser até 40% mais barato que o financiamento para quem pode esperar a contemplação." },
      { question: "Posso dar lance no consórcio?", answer: "Sim! Você pode ofertar lances mensais para aumentar suas chances de contemplação." },
      { question: "Posso comprar carro usado com consórcio?", answer: "Sim, após a contemplação você pode adquirir veículos novos ou seminovos." },
    ],
  },
  "consorcio-veiculos-pesados": {
    type: "Consórcio de Veículos Pesados",
    emoji: "🚛",
    title: "Simulação de Consórcio de Veículos Pesados",
    subtitle: "Caminhões, ônibus e máquinas sem juros",
    metaTitle: "Consórcio de Veículos Pesados | Patro Seguros Guarulhos",
    metaDescription: "Simule consórcio de caminhão, ônibus e veículos pesados. Sem juros, crédito alto. Patro Seguros.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "tipoVeiculo", label: "Tipo de Veículo", required: true, type: "select", options: ["Caminhão leve", "Caminhão pesado", "Carreta", "Ônibus", "Van", "Máquina pesada"] },
      { id: "valorCredito", label: "Valor do Crédito Desejado", required: true, type: "select", options: ["Até R$ 200 mil", "R$ 200 mil - R$ 500 mil", "R$ 500 mil - R$ 1 milhão", "Acima de R$ 1 milhão"] },
      { id: "prazo", label: "Prazo Desejado", required: true, type: "radio", options: ["60 meses", "80 meses", "100 meses", "120 meses"] },
    ],
    benefits: [
      { icon: "🚛", title: "Crédito alto", desc: "Valores de crédito para qualquer porte de veículo" },
      { icon: "💰", title: "Sem juros", desc: "Apenas taxa de administração, economia garantida" },
      { icon: "📊", title: "Parcelas flexíveis", desc: "Planos adaptados ao fluxo de caixa da empresa" },
    ],
    faqs: [
      { question: "Qual o prazo do consórcio de veículos pesados?", answer: "Os prazos variam de 60 a 120 meses, dependendo do valor do crédito e da administradora." },
      { question: "Empresa pode fazer consórcio?", answer: "Sim! Tanto pessoa física quanto jurídica podem adquirir cotas de consórcio." },
      { question: "Posso usar o crédito para veículo usado?", answer: "Sim, desde que o veículo esteja dentro dos critérios da administradora." },
    ],
  },
  "consorcio-geral": {
    type: "Consórcio",
    emoji: "🤝",
    title: "Simulação de Consórcio",
    subtitle: "Conquiste seus objetivos sem juros",
    metaTitle: "Consórcio em Guarulhos | Patro Seguros",
    metaDescription: "Simule seu consórcio. Imóveis, veículos, serviços e mais. Sem juros, parcelas acessíveis. Patro Seguros.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "modalidade", label: "Modalidade", required: true, type: "select", options: ["Imóveis", "Automóveis", "Veículos Pesados", "Motos", "Serviços", "Outro"] },
      { id: "valorCredito", label: "Valor do Crédito Desejado", placeholder: "R$ 100.000", required: true, type: "currency" },
      { id: "mensagem", label: "Mensagem (opcional)", placeholder: "Conte-nos mais sobre seu objetivo", required: false, type: "text" },
    ],
    benefits: [
      { icon: "🤝", title: "Diversas modalidades", desc: "Imóveis, veículos, serviços e mais" },
      { icon: "💰", title: "Sem juros", desc: "Economia real comparado ao financiamento" },
      { icon: "📋", title: "Sem burocracia", desc: "Processo simples e rápido" },
    ],
    faqs: [
      { question: "O que é consórcio?", answer: "É uma forma de compra planejada em grupo, onde os participantes contribuem mensalmente para um fundo comum, sem cobrança de juros." },
      { question: "Consórcio é seguro?", answer: "Sim! As administradoras são regulamentadas pelo Banco Central do Brasil." },
      { question: "Qual a diferença entre consórcio e financiamento?", answer: "No consórcio não há juros, apenas taxa de administração. No financiamento, os juros podem dobrar o valor do bem." },
    ],
  },
};

/* Map card titles to form config keys */
export const cardTitleToFormKey: Record<string, string> = {
  "Seguro Auto": "auto",
  "Seguro de Vida": "vida",
  "Seguro Residencial": "residencial",
  "Plano de Saúde": "saude",
  "Seguro Empresarial": "empresarial",
  "Consórcio Imóveis": "consorcio-imoveis",
  "Consórcio Carro": "consorcio-carro",
  "Consórcio Veículos Pesados": "consorcio-veiculos-pesados",
  "Consórcio Geral": "consorcio-geral",
};
