import type { InsuranceFormConfig } from "@/components/InsuranceQuoteForm";

export const formConfigs: Record<string, InsuranceFormConfig> = {
  auto: {
    type: "Seguro Auto",
    emoji: "🚗",
    title: "Cotação de Seguro Auto Grátis",
    subtitle: "Encontre o melhor preço para seu veículo em minutos",
    metaTitle: "Cotação de Seguro Auto Grátis em Guarulhos | Patro Seguros",
    metaDescription: "Solicite sua cotação gratuita de Seguro Auto. Comparamos Porto, Tokio Marine, Allianz, HDI e mais 16 seguradoras. Resposta em 2 horas.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "marca", label: "Marca do Veículo", required: true, type: "select", options: ["Fiat", "Volkswagen", "Chevrolet", "Ford", "Hyundai", "Toyota", "Honda", "Renault", "Jeep", "Nissan", "Peugeot", "Citroën", "BMW", "Mercedes-Benz", "Audi", "Outra"] },
      { id: "modelo", label: "Modelo", placeholder: "Ex: Civic, Onix, HB20...", required: true, type: "text" },
      { id: "ano", label: "Ano do Veículo", required: true, type: "select", options: Array.from({ length: 17 }, (_, i) => String(2026 - i)) },
      { id: "cobertura", label: "Tipo de Cobertura", required: true, type: "radio", options: ["Compreensiva (Roubo + Colisão + Incêndio)", "Parcial (Colisão + Incêndio)", "Terceiros (Responsabilidade Civil)"] },
    ],
    benefits: [
      { icon: "⚡", title: "Resposta em 2 horas", desc: "Cotações comparativas de várias seguradoras" },
      { icon: "💰", title: "Melhores preços", desc: "Comparamos 16+ seguradoras para você" },
      { icon: "🛡️", title: "Suporte completo", desc: "Acompanhamento em sinistros do início ao fim" },
    ],
    faqs: [
      { question: "Qual o seguro auto mais barato?", answer: "O preço varia conforme perfil, veículo e região. Comparamos todas as seguradoras para encontrar o menor valor com a melhor cobertura." },
      { question: "Como reduzir o valor do seguro auto?", answer: "Instalar rastreador, ter garagem, manter bônus e escolher franquia maior são formas eficazes de reduzir o prêmio." },
      { question: "Seguro auto fica mais caro para carros financiados?", answer: "Não necessariamente. Carros financiados precisam de cobertura compreensiva, mas comparando seguradoras é possível encontrar bons preços." },
      { question: "Preciso de cobertura compreensiva?", answer: "Recomendamos compreensiva para veículos de maior valor. Para carros mais antigos, a cobertura de terceiros pode ser suficiente." },
    ],
  },
  vida: {
    type: "Seguro de Vida",
    emoji: "❤️",
    title: "Cotação de Seguro de Vida Grátis",
    subtitle: "Proteja quem você ama com a melhor cobertura",
    metaTitle: "Cotação de Seguro de Vida Grátis | Patro Seguros Guarulhos",
    metaDescription: "Solicite cotação gratuita de Seguro de Vida. Coberturas a partir de R$ 100 mil. Aprovação rápida e sem burocracia. Patro Seguros.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "nascimento", label: "Data de Nascimento", required: true, type: "date" },
      { id: "profissao", label: "Profissão", placeholder: "Sua profissão", required: true, type: "text" },
      { id: "cobertura", label: "Cobertura Desejada", required: true, type: "radio", options: ["R$ 100 mil", "R$ 250 mil", "R$ 500 mil", "R$ 1 milhão", "Outro valor"] },
      { id: "tipo", label: "Tipo de Seguro", required: true, type: "radio", options: ["Seguro de Vida Individual", "Seguro de Vida em Grupo (empresa)"] },
    ],
    benefits: [
      { icon: "🔒", title: "Proteção garantida", desc: "Cobertura desde R$ 100 mil até R$ 2 milhões" },
      { icon: "💳", title: "Prêmios acessíveis", desc: "A partir de R$ 50/mês" },
      { icon: "⚡", title: "Aprovação rápida", desc: "Sem burocracia, análise em 24h" },
    ],
    faqs: [
      { question: "Quanto custa um seguro de vida?", answer: "A partir de R$ 50/mês, dependendo da idade, profissão e valor da cobertura escolhida." },
      { question: "Seguro de vida tem carência?", answer: "Para morte natural, algumas seguradoras aplicam carência de 24 meses. Para morte acidental, a cobertura é imediata." },
      { question: "Posso ter mais de um seguro de vida?", answer: "Sim! Você pode ter múltiplos seguros de vida de seguradoras diferentes." },
    ],
  },
  residencial: {
    type: "Seguro Residencial",
    emoji: "🏠",
    title: "Cotação de Seguro Residencial Grátis",
    subtitle: "Proteja seu lar com a melhor cobertura",
    metaTitle: "Cotação de Seguro Residencial Grátis | Patro Seguros Guarulhos",
    metaDescription: "Cotação gratuita de Seguro Residencial. Proteção contra incêndio, roubo, RC e mais. Compare seguradoras. Patro Seguros.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "tipoImovel", label: "Tipo de Imóvel", required: true, type: "radio", options: ["Apartamento", "Casa", "Condomínio"] },
      { id: "valorImovel", label: "Valor Estimado do Imóvel", placeholder: "R$ 300.000", required: true, type: "currency" },
      { id: "cep", label: "CEP", placeholder: "00000-000", required: true, type: "text" },
      { id: "coberturas", label: "Coberturas Desejadas", required: true, type: "checkbox-group", options: ["Incêndio", "Roubo", "Responsabilidade Civil", "Vidros", "Todos"] },
    ],
    benefits: [
      { icon: "🔐", title: "Proteção completa", desc: "Incêndio, roubo, responsabilidade civil e vidros" },
      { icon: "📍", title: "Análise por CEP", desc: "Preço justo de acordo com sua região" },
      { icon: "🚨", title: "Sinistro 24h", desc: "Atendimento emergencial a qualquer hora" },
    ],
    faqs: [
      { question: "Seguro residencial cobre roubo?", answer: "Sim, a cobertura de roubo e furto qualificado pode ser incluída no seguro residencial." },
      { question: "Quanto custa um seguro residencial?", answer: "A partir de R$ 15/mês para apartamentos. O valor varia conforme tipo de imóvel, localização e coberturas." },
      { question: "Inquilino pode contratar seguro residencial?", answer: "Sim! Inquilinos podem contratar seguro para proteger seus bens e o conteúdo do imóvel." },
    ],
  },
  saude: {
    type: "Plano de Saúde",
    emoji: "🏥",
    title: "Cotação de Plano de Saúde Grátis",
    subtitle: "Saúde em dia, proteção garantida",
    metaTitle: "Cotação de Plano de Saúde Grátis em Guarulhos | Patro Seguros",
    metaDescription: "Compare planos de saúde das melhores operadoras. Cotação gratuita para pessoa física e empresas. Resposta em 2h. Patro Seguros.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "vidas", label: "Número de Vidas", required: true, type: "radio", options: ["1 pessoa", "2-3 pessoas", "4-5 pessoas", "6+ pessoas"] },
      { id: "faixaEtaria", label: "Faixa Etária Principal", required: true, type: "radio", options: ["Até 30 anos", "31-45 anos", "46-60 anos", "60+ anos"] },
      { id: "tipoCobertura", label: "Tipo de Cobertura", required: true, type: "radio", options: ["Básico (Ambulatorial + Hospitalar)", "Intermediário (+ Odonto)", "Premium (Tudo + Fisio + Psicologia)"] },
      { id: "temEmpresa", label: "Tem Empresa?", required: true, type: "radio", options: ["Pessoa Física", "Empresa (PME)"] },
    ],
    benefits: [
      { icon: "🏥", title: "Rede ampla", desc: "Mais de 20 operadoras e milhares de prestadores" },
      { icon: "💰", title: "Preços competitivos", desc: "Comparamos as melhores operadoras do mercado" },
      { icon: "📋", title: "Sem burocracia", desc: "Análise rápida e aprovação em 24h" },
    ],
    faqs: [
      { question: "Qual o plano de saúde mais barato?", answer: "Planos com coparticipação e rede regional costumam ter os menores valores. Comparamos todas as opções para seu perfil." },
      { question: "Empresa com 2 funcionários pode ter plano empresarial?", answer: "Sim! A maioria das operadoras aceita a partir de 2 vidas para planos PME, com preços até 40% menores." },
      { question: "Plano de saúde tem carência?", answer: "Sim, carências variam de 24h a 300 dias conforme o procedimento. Para portabilidade, as carências podem ser eliminadas." },
    ],
  },
  empresarial: {
    type: "Seguro Empresarial",
    emoji: "🏢",
    title: "Cotação de Seguro Empresarial Grátis",
    subtitle: "Proteja seu negócio com segurança total",
    metaTitle: "Cotação de Seguro Empresarial Grátis | Patro Seguros Guarulhos",
    metaDescription: "Cotação gratuita de Seguro Empresarial. Proteção para comércio, indústria e serviços. Compare seguradoras. Patro Seguros.",
    fields: [
      { id: "nome", label: "Nome Completo", placeholder: "Seu nome completo", required: true, type: "text" },
      { id: "email", label: "E-mail", placeholder: "seu@email.com", required: true, type: "email" },
      { id: "telefone", label: "Telefone/WhatsApp", placeholder: "(11) 99999-9999", required: true, type: "tel" },
      { id: "razaoSocial", label: "Razão Social", placeholder: "Nome da empresa", required: true, type: "text" },
      { id: "ramo", label: "Ramo de Atividade", required: true, type: "select", options: ["Comércio", "Serviços", "Indústria", "Saúde", "Tecnologia", "Agronegócio", "Outro"] },
      { id: "faturamento", label: "Faturamento Anual Estimado", placeholder: "R$ 500.000", required: true, type: "currency" },
      { id: "coberturas", label: "Coberturas Desejadas", required: true, type: "checkbox-group", options: ["Incêndio", "Roubo", "Responsabilidade Civil", "Vidros", "Equipamentos", "Todos"] },
    ],
    benefits: [
      { icon: "🛡️", title: "Proteção total", desc: "Incêndio, roubo, RC, equipamentos e vidros" },
      { icon: "📊", title: "Análise personalizada", desc: "Cobertura de acordo com seu ramo e faturamento" },
      { icon: "⚡", title: "Resposta rápida", desc: "Cotação em até 2 horas com comparativo" },
    ],
    faqs: [
      { question: "Seguro empresarial é obrigatório?", answer: "Não é obrigatório por lei na maioria dos casos, mas é essencial para proteger o patrimônio da empresa contra imprevistos." },
      { question: "O que o seguro empresarial cobre?", answer: "Incêndio, roubo, responsabilidade civil, danos elétricos, vendaval, equipamentos e muito mais, conforme o plano escolhido." },
      { question: "Quanto custa seguro empresarial?", answer: "Depende do ramo, localização e valor segurado. Pode começar em R$ 80/mês para comércios pequenos." },
    ],
  },
};

/* Map card titles to form config keys */
export const cardTitleToFormKey: Record<string, string> = {
  "Seguro Auto": "auto",
  "Seguro de Vida": "vida",
  "Seguro Residencial": "residencial",
  "Plano de Saúde": "saude",
  "Seguro Empresarial": "empresarial",
};
