ALTER TABLE public.contacts 
ADD COLUMN IF NOT EXISTS marital_status TEXT,
ADD COLUMN IF NOT EXISTS partner_name TEXT,
ADD COLUMN IF NOT EXISTS partner_birthday DATE,
ADD COLUMN IF NOT EXISTS has_children BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS children_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS children_data JSONB DEFAULT '[]'::jsonb,
ADD COLUMN IF NOT EXISTS car_count INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS has_motorcycle BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS has_life_insurance BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS has_home_insurance BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS health_plan_type TEXT,
ADD COLUMN IF NOT EXISTS has_business_insurance BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS has_other_insurance BOOLEAN DEFAULT false;